baseURL = 'https://tokenofhonor.com/'
languageCode = 'en-us'
title = 'Token of Honor'
theme = 'PaperMod'

[params]
  description = "A personal blog about earning tokens of honor"
  author = "TOH"
  
[params.homeInfoParams]
  Title = "Token of Honor"
  Content = "A personal blog about earning tokens of honor"

[[menu.main]]
  name = "Archive"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 20